version: '3.9'

services:
  balancer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - CONFIG_PATH=local.yaml
    ports:
      - "9080:9080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    tty: true
    stdin_open: true